# Generated by Django 5.1.6 on 2025-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('secretaria', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('credito_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('compromiso', models.DecimalField(decimal_places=2, max_digits=15)),
                ('disponible', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
