# Generated by Django 5.1.6 on 2025-02-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='año',
            field=models.IntegerField(default=2025),
        ),
    ]
