# Generated by Django 5.1.6 on 2025-02-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_presupuesto_año'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presupuesto',
        ),
    ]
