# Generated by Django 4.2.18 on 2025-07-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='area',
            field=models.IntegerField(default=-1),
        ),
    ]
