# Generated by Django 4.2.18 on 2025-07-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_alter_userprofile_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='area',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='areas_permitidas',
            field=models.CharField(default=0, help_text='Ej: 10,20,21', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
