# Generated by Django 5.1.6 on 2025-05-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargar_csv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('categoria', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
