# Generated by Django 5.1.6 on 2025-06-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargar_csv', '0002_tipogasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='reestructuras',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
