# Generated by Django 4.2.18 on 2025-07-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargar_csv', '0003_presupuesto_reestructuras'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviGast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xx', models.CharField(max_length=2)),
                ('yy', models.CharField(max_length=2)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mes', models.PositiveSmallIntegerField()),
                ('año', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Movimiento de Gasto',
                'verbose_name_plural': 'Movimientos de Gastos',
            },
        ),
    ]
