# Generated by Django 4.2.18 on 2025-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargar_csv', '0004_movigast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movigast',
            options={},
        ),
        migrations.RenameField(
            model_name='movigast',
            old_name='xx',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='movigast',
            old_name='yy',
            new_name='gasto',
        ),
        migrations.AddField(
            model_name='movigast',
            name='actividad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
